apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: hq-db-data
  name: hq-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
