apiVersion: v1
data:
  logstash.conf: |
    input {
      jdbc {
        jdbc_connection_string => "jdbc:postgresql://hq-db:5432/hq_db"
        jdbc_user => "hq_user"
        jdbc_password => "hq_pass"
        jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-42.2.24.jar"
        jdbc_driver_class => "org.postgresql.Driver"
        schedule => "* * * * *" # Run every minute
        statement => "SELECT * FROM your_table"
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "server-sync-%{+yyyy.MM.dd}"
      }
      stdout { codec => rubydebug }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: logstash
  name: logstash-cm0
