apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../ndrc_demo/docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: trailer
  name: trailer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trailer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../ndrc_demo/docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: trailer
    spec:
      containers:
        - image: trailer
          name: trailer
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/app.py
              name: trailer-cm0
              subPath: app.py
            - mountPath: /app/templates
              name: trailer-cm1
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: app.py
                path: app.py
            name: trailer-cm0
          name: trailer-cm0
        - configMap:
            name: trailer-cm1
          name: trailer-cm1
