apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../ndrc_demo/docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: trailer
  name: trailer
spec:
  ports:
    - name: "5003"
      port: 5003
      targetPort: 5000
  selector:
    io.kompose.service: trailer
